"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { corpusSchema, emptyResume, resumeSchema, type Corpus, type Project, type Resume } from "@/lib/workbench/schemas";
import { populateTemplate, rankProjects } from "@/lib/workbench/ranking";
import { integrationSlots } from "@/lib/workbench/integrations";
import styles from "./workbench.module.css";
import AiLab from "./ai-lab";

const tabs=["Explore questions","Resume lab","Project relevance","AI playground","Integration slots"] as const;
type Tab=typeof tabs[number];
async function api(operation:string,init?:RequestInit) {
  const response=await fetch(`/api/dev/${operation}`,{...init,cache:"no-store"});
  const value=await response.json();
  if(!response.ok) throw new Error(value.error?.message||"Request failed.");
  return value;
}
export default function Workbench() {
  const [tab,setTab]=useState<Tab>(tabs[0]);const [corpus,setCorpus]=useState<Corpus|null>(null);
  const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");
  const [family,setFamily]=useState("");const [specialty,setSpecialty]=useState("");
  const [technology,setTechnology]=useState("");const [search,setSearch]=useState("");const [category,setCategory]=useState("");
  const [page,setPage]=useState(0);const [selected,setSelected]=useState("");
  const [text,setText]=useState("");const [consent,setConsent]=useState(false);const [reviewed,setReviewed]=useState(false);
  const [aiSession,setAiSession]=useState(0);
  const [profile,setProfile]=useState<Resume>(emptyResume);const [chosenProject,setChosenProject]=useState("");
  const level=profile.experienceLevel==="unknown"?"":profile.experienceLevel;
  const [accountVersion,setAccountVersion]=useState<number|null>(null),[analysisDate,setAnalysisDate]=useState("");
  async function accountRequest(save=false){
    const response=await fetch("/api/profile",{method:save?"PUT":"GET",headers:save?{"Content-Type":"application/json"}:undefined,body:save?JSON.stringify({profile,version:accountVersion,confirmed:true}):undefined,cache:"no-store"});
    const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Profile request failed");
    setAnalysisDate(data.analysisDate);setAccountVersion(data.account?.version??null);
    if(data.account){setProfile(resumeSchema.parse(data.account.profile));setReviewed(true);setAiSession(n=>n+1);}
    setNotice(save?"Profile saved to your signed-in account; experience classified automatically.":data.account?"Saved account profile loaded.":"No saved profile yet. Parse and review a resume, then save it to your account.");
  }
  const [status,setStatus]=useState<{geminiConfigured:boolean;model:string}|null>(null);
  async function run(label:string,action:()=>Promise<void>){setBusy(label);setError("");setNotice("");try{await action();}catch(e){setError(e instanceof Error?e.message:"Something went wrong.");}finally{setBusy("");}}
  useEffect(()=>{let active=true;Promise.all([api("corpus"),api("status")]).then(([c,s])=>{if(active){setCorpus(corpusSchema.parse(c));setStatus(s);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  useEffect(()=>{let active=true;fetch("/api/profile",{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Could not load your profile");if(active){setAnalysisDate(data.analysisDate);setAccountVersion(data.account?.version??null);if(data.account){setProfile(resumeSchema.parse(data.account.profile));setReviewed(true);}}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  const role=corpus?.roles.find(r=>r.id===family);
  const filtered=useMemo(()=>corpus?.questions.filter(q=>(!family||q.familyId===family)&&(!specialty||q.specialtyIds.includes(specialty))&&(!level||q.level.includes(level))&&(!technology||q.technologies.includes(technology))&&(!category||q.category===category)&&(!search||`${q.prompt} ${q.competency} ${q.intent}`.toLowerCase().includes(search.toLowerCase())))??[],[corpus,family,specialty,level,technology,category,search]);
  const actualPage=Math.min(page,Math.max(0,Math.ceil(filtered.length/12)-1));
  const current=filtered.find(q=>q.id===selected)??filtered[actualPage*12];
  const rubric=corpus?.rubrics.find(r=>r.id===current?.rubricId);
  const ranked=rankProjects(profile.projects,role,technology?[technology]:[]);
  const project=profile.projects.find(p=>p.id===chosenProject)??ranked[0]?.project;
  function patchProject(id:string,patch:Partial<Project>){setProfile(p=>({...p,projects:p.projects.map(x=>x.id===id?{...x,...patch}:x)}));setReviewed(false);}
  function resetFilters(){setFamily("");setSpecialty("");setTechnology("");setSearch("");setCategory("");setPage(0);}
  const control=(label:string,value:string,onChange:(v:string)=>void,options:{id:string;label:string}[],placeholder:string)=><label className={styles.field}>{label}<select value={value} onChange={e=>{onChange(e.target.value);setPage(0);}}><option value="">{placeholder}</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>;
  const headings:Record<Tab,{title:string;description:string}>={
    "Explore questions":{title:"A better place to start.",description:"Find the questions that fit your role. Look past the prompt and into what a good answer reveals."},
    "Resume lab":{title:"Start with your experience.",description:"Bring your resume, review the evidence, and build a profile that tells your story accurately."},
    "Project relevance":{title:"Find your strongest story.",description:"See how your projects connect to a role, with the evidence and missing details in view."},
    "AI playground":{title:"Make practice personal.",description:"Turn your experience into an interview. Explore questions, submit answers, and decide what to remember."},
    "Integration slots":{title:"The next parts of the picture.",description:"See what is connected, what is ready for a handoff, and what is still to come."},
  };
  return <main className={styles.shell}>
    <a className={styles.skip} href="#workbench-content">Skip to workspace</a>
    <div className={styles.masthead}><Link href="/" className={styles.wordmark}>Get Me Hired<span className={styles.wordmarkAccent}>.</span></Link><span className={styles.workspaceLabel}>Development workspace</span><span className={styles.datasetStatus}>{corpus?"Research library loaded":"Loading research library"}</span></div>
    <nav className={styles.tabs} aria-label="Workbench sections">{tabs.map((t,i)=><button key={t} aria-current={tab===t?"page":undefined} onClick={()=>setTab(t)}><span className={styles.tabNumber}>{String(i+1).padStart(2,"0")}</span>{t}</button>)}</nav>
    <header className={styles.hero} id="workbench-content"><div><p className={styles.eyebrow}>{tab}</p><h1>{headings[tab].title}</h1><p className={styles.subtitle}>{headings[tab].description}</p></div><div className={styles.stamp}><span>Built around your experience</span><p>Practice with context.<br/>Review with evidence.</p><small>Private workspace · no hiring scores</small></div></header>
    <div className={styles.stats}><div><strong>{corpus?.questions.length.toLocaleString()??"…"}</strong><span>question probes</span></div><div><strong>{corpus?.roles.length??"…"}</strong><span>role families</span></div><div><strong>{corpus?.manifest.specialtyCount??"…"}</strong><span>specialties</span></div><div><strong>{corpus?.sources.length??"…"}</strong><span>reference sources</span></div></div>
    {error&&<div role="alert" className={styles.error}>{error}<button onClick={()=>run("Reloading",async()=>{const [c,s]=await Promise.all([api("corpus"),api("status")]);setCorpus(corpusSchema.parse(c));setStatus(s);})}>Reload configuration</button></div>}
    <p className={styles.live} aria-live="polite">{busy||notice}</p>
    {(tab==="Explore questions"||tab==="Project relevance"||tab==="AI playground")&&<section className={styles.filters} aria-label="Role choices">
      {control("Role family",family,v=>{setFamily(v);setSpecialty("");setTechnology("");},corpus?.roles??[],"General / not sure")}
      {control("Specialty",specialty,setSpecialty,role?.specialties??[],"Any specialty")}
      <div className={styles.experience}><span>Experience</span><strong>{profile.experienceLevel==="unknown"?"Awaiting your profile":profile.experienceLevel}</strong><small>Assigned from resume evidence</small></div>
      {control("Technology · optional",technology,setTechnology,(role?.technologies??[]).map(t=>({id:t,label:t})),"No preference")}
    </section>}
    {tab==="Explore questions"&&<>
      <div className={styles.searchbar}><label className={styles.field}>Search questions<input placeholder="Try debugging, migration, accessibility…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label>{control("Interview category",category,setCategory,[{id:"behavioral",label:"Behavioral"},{id:"technical-behavioral",label:"Technical-behavioral"}],"Both categories")}<button onClick={resetFilters}>Reset filters</button></div>
      <div className={styles.resultsTitle}><h2>Question library</h2><span>{filtered.length} matches · original editorial drafts</span></div>
      <div className={styles.explorer}><div className={styles.list}>
        {filtered.slice(actualPage*12,actualPage*12+12).map(q=><button className={`${styles.question} ${current?.id===q.id?styles.active:""}`} key={q.id} onClick={()=>setSelected(q.id)}><span>{q.category} <b>↗</b></span><p>{q.prompt}</p><small>{q.competency} · {q.level.join(" / ")}</small></button>)}
        {!filtered.length&&<p className={styles.empty}>{corpus?"No matches. Try a broader role or clear a filter.":"Load a local dataset to browse questions."}</p>}
        <div className={styles.pagination}><button disabled={actualPage===0} onClick={()=>{setPage(actualPage-1);setSelected("");}}>← Previous</button><span>{actualPage+1} / {Math.max(1,Math.ceil(filtered.length/12))}</span><button disabled={(actualPage+1)*12>=filtered.length} onClick={()=>{setPage(actualPage+1);setSelected("");}}>Next →</button></div>
      </div><aside className={styles.detail}>{current?<><p className={styles.eyebrow}>QUESTION NOTES</p><h2>{current.prompt}</h2><span className={styles.badge}>{current.competency}</span><h3>What this explores</h3><p>{current.intent}</p><h3>Listen for</h3><ul>{current.strongAnswerIndicators.map(s=><li key={s}>{s}</li>)}</ul><h3>Follow-ups</h3><ul>{current.followUps.map(s=><li key={s}>{s}</li>)}</ul><h3>Rubric anchors</h3>{rubric&&Object.entries(rubric.anchors).map(([k,v])=><p key={k}><b>{k}/5</b> — {v}</p>)}<p>{rubric?.insufficientEvidence}</p><h3>Experience guidance</h3><p>{current.earlyCareerGuidance}</p><details><summary>Senior extension & personalization fields</summary><p>{current.seniorExtension}</p><p>{current.personalizationFields.join(", ")}</p></details><h3>Topic references</h3>{current.sourceIds.map(id=>{const s=corpus?.sources.find(s=>s.id===id);return s?<p key={id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><small className={styles.block}>{s.publisher} · accessed {s.accessedAt}</small><small>{s.scope}</small></p>:null;})}<p className={styles.note}>Original practice questions, not claims about what an employer asks. Rubrics require human review.</p></>:<p>Select a question to inspect its context.</p>}</aside></div>
      <details className={styles.method}><summary>Methodology, classification rules and limitations</summary>{corpus?.methodology.approach.map(s=><p key={s}>{s}</p>)}<h3>Limitations</h3><ul>{corpus?.methodology.limitations.map(s=><li key={s}>{s}</li>)}</ul><h3>Resume classification</h3><p>{corpus?.classification.unknownPolicy}</p>{corpus?.classification.experienceLevels.map(l=><p key={l.id}><b>{l.id}:</b> {l.rule}</p>)}</details>
    </>}
    {tab==="Resume lab"&&<div className={styles.lab}><section className={styles.panel}><p className={styles.eyebrow}>01 / EXTRACT & REVIEW</p><h2>Bring your experience.</h2><p>Upload a PDF or DOCX (up to 10 MB), or paste text. Extraction stays on this server. No uploaded file is retained.</p><label className={styles.upload}>Choose a resume<input type="file" accept=".pdf,.docx" disabled={!!busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run("Extracting resume",async()=>{const r=await api("extract",{method:"POST",headers:{"x-file-name":file.name},body:file});setText(r.text);setConsent(false);setProfile(emptyResume);setReviewed(false);setNotice(r.warnings.join(" "));});e.target.value="";}}/></label><label className={styles.field}>Extracted or pasted text<textarea rows={14} value={text} maxLength={60000} placeholder="Your resume text appears here. Review it before sending." onChange={e=>{setText(e.target.value);setConsent(false);setReviewed(false);}}/></label><p className={styles.note}>Scanned or encrypted PDF? Paste readable text instead. OCR is not included.</p><label className={styles.check}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send this reviewed text to Google Gemini for structured parsing.</label><button className={styles.primary} disabled={!!busy||!consent||text.trim().length<30} onClick={()=>run("Parsing with Gemini",async()=>{const r=await api("parse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,consent})});setProfile(resumeSchema.parse(r.profile));setReviewed(false);setNotice(`Parsed with ${r.model}. Review the profile before ranking.`);})}>Parse with Gemini →</button><p className={styles.note}>{status?.geminiConfigured?`Key configured · ${status.model} · connection verified only after a successful parse`:"Gemini key not configured"}</p></section>
      <section className={styles.panel}><p className={styles.eyebrow}>02 / CONFIRM THE FACTS</p><h2>Your structured profile</h2><p>AI-assigned experience: <strong>{profile.experienceLevel}</strong></p><p>Correct the underlying education and work facts; experience is reclassified on account save and question generation.</p>
        <div className={styles.actions}><button disabled={!!busy} onClick={()=>run("Loading account profile",()=>accountRequest())}>Load my saved profile</button><button disabled={!!busy||!reviewed} onClick={()=>run("Classifying and saving profile",()=>accountRequest(true))}>Save to my account</button></div>
        <p>{analysisDate?`Analysis date: ${analysisDate} (UTC)`:"Date is supplied by the server, not the model's training cutoff."}</p>
        <p>{profile.experienceReason}</p><label className={styles.field}>Skills (comma separated)<input value={profile.skills.join(", ")} onChange={e=>{setProfile(p=>({...p,skills:e.target.value.split(",").map(s=>s.trim()).filter(Boolean)}));setReviewed(false);}}/></label>
        {profile.warnings.length>0&&<details open><summary>Extraction warnings</summary><ul>{profile.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}
        <details><summary>Other resume sections ({profile.sections.length})</summary><p>Inspect the evidence; use the JSON editor below to correct these fields.</p>{profile.sections.map((s,i)=><div key={i}><h3>{s.kind}: {s.title}</h3><p>{s.organization} · {s.dates}</p><blockquote>{s.evidence.join("\n")}</blockquote></div>)}</details>
        {profile.projects.map(p=><details key={p.id} className={styles.projectEdit} open><summary>{p.name||"Untitled project"}</summary>{(["name","description","contribution"] as const).map(key=><label key={key} className={styles.field}>{key}<textarea rows={key==="name"?1:2} value={p[key]??""} onChange={e=>patchProject(p.id,{[key]:e.target.value|| (key==="contribution"?null:"")})}/></label>)}{(["skills","competencies","decisions","outcomes","evidence"] as const).map(key=><label className={styles.field} key={key}>{key} (one per line)<textarea rows={2} value={p[key].join("\n")} onChange={e=>patchProject(p.id,{[key]:e.target.value.split("\n").filter(Boolean)})}/></label>)}<button onClick={()=>{setProfile(r=>({...r,projects:r.projects.filter(x=>x.id!==p.id)}));setReviewed(false);}}>Remove project</button></details>)}
        <button onClick={()=>{setProfile(p=>({...p,projects:[...p.projects,{id:crypto.randomUUID(),name:"",description:"",skills:[],competencies:[],contribution:null,decisions:[],outcomes:[],evidence:[]}]}));setReviewed(false);}}>+ Add a project manually</button>
        <details><summary>Advanced: edit profile facts</summary><ProfileJson profile={profile} onApply={p=>{setProfile({...p,experienceLevel:profile.experienceLevel,experienceReason:profile.experienceReason});setReviewed(false);}}/></details>
        <label className={styles.check}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed these fields and corrected unsupported claims.</label><div className={styles.actions}><button className={styles.primary} disabled={!reviewed||!profile.projects.length} onClick={()=>setTab("Project relevance")}>Inspect project relevance →</button><button disabled={!!busy||!reviewed} onClick={()=>run("Exporting profile",async()=>{const r=await api("export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile})});setNotice(r.message);})}>Save local JSON</button><button onClick={()=>{setProfile(emptyResume);setText("");setReviewed(false);setConsent(false);setAiSession(n=>n+1);setNotice("Resume, profile and AI session cleared from this page.");}}>Clear session</button></div>
      </section></div>}
    {tab==="Project relevance"&&<><div className={styles.resultsTitle}><h2>Choose the story worth exploring.</h2><span>Deterministic preview · not candidate scoring</span></div>{!reviewed?<div className={styles.empty}><h3>Review a profile first</h3><p>Parse a resume or enter projects, then confirm the facts.</p><button className={styles.primary} onClick={()=>setTab("Resume lab")}>Open resume lab</button></div>:<div className={styles.lab}><section>{ranked.map((r,i)=><article className={styles.rankCard} key={r.project.id}><span className={styles.badge}>#{i+1} · {r.score??"—"} relevance index · {r.coverage}% coverage</span><h2>{r.project.name}</h2><p>{r.project.description}</p><div className={styles.componentGrid}>{Object.entries(r.components).map(([k,v])=><div key={k}><small>{k}</small><strong>{v===null?"Unknown":`${v}/100`}</strong></div>)}</div><p>Matched terms: {r.matched.join(", ")||"None"}</p><p>Missing evidence: {r.missing.join(", ")||"None in this heuristic"}</p><details><summary>Why this ranking?</summary><p>{r.explanation}</p><p>Weights: role relevance 35%, competency evidence 25%, ownership 15%, technical decisions 15%, outcomes 10%. Observed components are normalized; high indices with low coverage are not equivalent to well-evidenced profiles. Exact lexical matches can miss synonyms.</p></details><button onClick={()=>setChosenProject(r.project.id)}>Use this project for previews</button></article>)}</section><aside className={styles.detail}><p className={styles.eyebrow}>PERSONALIZED TEMPLATE PREVIEWS</p><h2>{project?.name||"Choose a project"}</h2><p>These use confirmed fields and curated templates. They do not call an AI model.</p>{corpus?.templates.map(t=>{const result=populateTemplate(t.prompt,project);return <article className={styles.template} key={t.id}><span className={styles.badge}>{t.intent}</span><p>{result.text}</p>{result.missing.length>0&&<small>Missing: {result.missing.join(", ")}</small>}</article>;})}</aside></div>}</>}
    {tab==="Integration slots"&&<><h2>Room for the next layer.</h2><p className={styles.subtitle}>Gemini and Backboard tools are in AI playground. Recording, voice and camera integrations remain future work.</p><div className={styles.slots}>{integrationSlots.map(s=><article className={styles.panel} key={s.id}><span className={styles.badge}>{s.status}</span><h2>{s.name}</h2><p>{s.detail}</p>{(s.id==="generation"||s.id==="memory")?<button onClick={()=>setTab("AI playground")}>Open AI playground →</button>:<button disabled>Not connected</button>}</article>)}</div></>}
    <div hidden={tab!=="AI playground"}><AiLab key={aiSession} profile={reviewed?profile:undefined} target={{familyId:family,specialtyId:specialty,level:(level||"unknown") as Resume["experienceLevel"],technologies:technology?[technology]:[],description:""}} onResume={()=>setTab("Resume lab")}/></div>
    <footer className={styles.footer}>GET ME HIRED <span>Private development workbench · research stays outside the repository</span></footer>
  </main>;
}
function ProfileJson({profile,onApply}:{profile:Resume;onApply:(p:Resume)=>void}) {
 const [draft,setDraft]=useState("");const [error,setError]=useState("");
 return <div><button onClick={()=>setDraft(JSON.stringify(profile,null,2))}>Load current JSON</button><label className={styles.field}>Profile JSON<textarea rows={10} value={draft} onChange={e=>setDraft(e.target.value)}/></label><button onClick={()=>{try{const p=resumeSchema.parse(JSON.parse(draft));if(new Set(p.projects.map(x=>x.id)).size!==p.projects.length)throw new Error("Project IDs must be unique.");onApply(p);setError("");}catch{setError("Invalid profile JSON or duplicate project IDs. Check the schema and try again.");}}}>Apply validated JSON</button>{error&&<p role="alert">{error}</p>}</div>;
}
