[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
get_me_hired = "eZqUe8be2q8R6akfzAx9BZuQ4DnXezGbfTRPJZPpxk2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
