-- 0011: allow the 180-second blitz demo budget alongside the standard budgets.
-- Drops the previous time_budget_seconds CHECK by definition (its autogenerated
-- name varies) and re-adds it with 180 included. Existing rows (600/1200/1800)
-- already satisfy the new constraint, so validation is a no-op.
DO $$
DECLARE
  budget_constraint text;
BEGIN
  SELECT conname INTO budget_constraint
  FROM pg_constraint
  WHERE conrelid = 'interview_session_configs'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%time_budget_seconds%';
  IF budget_constraint IS NOT NULL THEN
    EXECUTE format('ALTER TABLE interview_session_configs DROP CONSTRAINT %I', budget_constraint);
  END IF;
END $$;

ALTER TABLE interview_session_configs
  ADD CHECK (time_budget_seconds IN (180, 600, 1200, 1800));
